"""Emit MetaPost from the figure spec.

Interface contract:
    emit(spec) -> str        complete MetaPost source, self-contained
The emitter makes NO layout decisions: every coordinate comes from the spec.
Only transform applied is the y-flip (spec is y-down, MetaPost is y-up).
"""
import figspec

TEX_ESC = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
           "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
           "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}

STYLE = {
    "feed":     ("#3c3836", 0.9, None),
    "fallback": ("#665c54", 0.8, "evenly scaled 1.4"),
    "escalate": ("#af3a03", 1.5, None),
    "store":    ("#7c6f64", 0.8, "dashpattern(on 2.2 off 2.2)"),
}


def tex_escape(s):
    return "".join(TEX_ESC.get(c, c) for c in s)


def rgb(h):
    h = h.lstrip("#")
    return "(%.4f,%.4f,%.4f)" % tuple(int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def emit(spec):
    C = spec["canvas"]
    H = C["h"]
    band = C["label_band"]
    pal = spec["palette"]
    res = figspec.resolve(spec)

    def fy(y):
        return H - y

    L = []
    a = L.append
    a("%% generated by emit_mp.py from the figure spec -- do not edit by hand")
    fmt = spec.get("_outputformat", "pdf")
    if fmt == "pdf":
        a('outputformat := "pdf";')
        a('outputtemplate := "%j.pdf";')
    else:
        a("prologues := 3;")
        a('outputtemplate := "%j.eps";')
    a("ahlength := 4.5; ahangle := 28;")
    a("verbatimtex")
    for line in spec.get("tex_preamble", [r"\documentclass{article}"]):
        a(line)
    a(r"\begin{document}")
    a("etex")
    a("")
    a("vardef rrect(expr ll, ur, r) =")
    a("  save p; path p;")
    a("  p = (xpart ll + r, ypart ll)")
    a("    -- (xpart ur - r, ypart ll) {right} .. {up} (xpart ur, ypart ll + r)")
    a("    -- (xpart ur, ypart ur - r)  {up} .. {left} (xpart ur - r, ypart ur)")
    a("    -- (xpart ll + r, ypart ur)  {left} .. {down} (xpart ll, ypart ur - r)")
    a("    -- (xpart ll, ypart ll + r)  {down} .. {right} cycle;")
    a("  p")
    a("enddef;")
    a("")
    a("beginfig(1);")
    a("  path pp; picture lbl;")
    a("  %% canvas guard: keeps the EPS BoundingBox equal to the declared canvas")
    a("  path canvasbox; canvasbox = (0,0)--(%d,0)--(%d,%d)--(0,%d)--cycle;"
      % (C["w"], C["w"], H, H))
    a("  draw canvasbox withcolor white;")
    a("")

    # ---- groups (fill + border + titles) ------------------------------------
    a("  %% ---- groups ----")
    for g in spec["groups"]:
        x0, y0, x1, y1 = figspec.group_rect(g)
        p = pal[g["tone"]]
        a("  %% group %s" % g["id"])
        a("  pp := rrect((%g,%g),(%g,%g),7);" % (x0, fy(y1), x1, fy(y0)))
        a("  fill pp withcolor %s;" % rgb(p["fill"]))
        a("  draw pp withcolor %s withpen pencircle scaled 0.9;" % rgb(p["stroke"]))
        a("  draw (%g,%g)--(%g,%g) withcolor %s withpen pencircle scaled 0.4;"
          % (x0, fy(y0 + band), x1, fy(y0 + band), rgb(p["stroke"])))
        a(r"  label(btex {\fontsize{9.5}{11}\selectfont\bfseries %s} etex, (%g,%g));"
          % (tex_escape(g["title"]), (x0 + x1) / 2.0, fy(y0 + 12)))
        a(r"  label(btex {\fontsize{7}{8}\selectfont %s} etex, (%g,%g));"
          % (tex_escape(g["sub"]), (x0 + x1) / 2.0, fy(y0 + 24)))
    a("")

    # ---- edges (drawn under the node boxes) ---------------------------------
    a("  %% ---- edges ----")
    for e in spec["edges"]:
        p, q = figspec.edge_points(spec, e, res)
        col, wid, dash = STYLE[e["kind"]]
        d = (" dashed " + dash) if dash else ""
        a("  drawarrow (%g,%g)--(%g,%g)%s withcolor %s withpen pencircle scaled %g;"
          % (p[0], fy(p[1]), q[0], fy(q[1]), d, rgb(col), wid))
    a("")

    # ---- nodes --------------------------------------------------------------
    a("  %% ---- nodes ----")
    for n in spec["nodes"]:
        x0, y0, x1, y1 = figspec.node_rect(n)
        p = pal[n["tone"]]
        store = n.get("shape", "box") == "store"
        r = 8 if store else 4
        wpen = 1.2 if store else 0.8
        a("  %% node %s" % n["id"])
        a("  pp := rrect((%g,%g),(%g,%g),%g);" % (x0, fy(y1), x1, fy(y0), r))
        a("  fill pp withcolor %s;" % rgb(p["node"]))
        a("  draw pp withcolor %s withpen pencircle scaled %g;"
          % (rgb(p["stroke"]), wpen))
        face = r"\texttt" if n.get("mono") else r"\bfseries"
        size = 9 if store else 8.5
        if "sub" in n:
            dy = n["h"] / 4.0
            a(r"  lbl := btex {\fontsize{%g}{%g}\selectfont %s{%s}} etex;"
              % (size, size + 2, face, tex_escape(n["label"])))
            a("  label(lbl, (%g,%g));" % (n["x"], fy(n["y"] - dy)))
            a(r'  write "LW %s " & decimal(xpart(urcorner lbl - llcorner lbl)) to "labelwidths.txt";'
              % n["id"])
            a(r"  label(btex {\fontsize{7}{8.5}\selectfont %s} etex, (%g,%g));"
              % (tex_escape(n["sub"]), n["x"], fy(n["y"] + dy)))
        else:
            a(r"  lbl := btex {\fontsize{%g}{%g}\selectfont %s{%s}} etex;"
              % (size, size + 2, face, tex_escape(n["label"])))
            a("  label(lbl, (%g,%g));" % (n["x"], fy(n["y"])))
            a(r'  write "LW %s " & decimal(xpart(urcorner lbl - llcorner lbl)) to "labelwidths.txt";'
              % n["id"])
    a("endfig;")
    a('write "END" to "labelwidths.txt";')
    a("end.")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    import sys
    spec = figspec.load(sys.argv[1] if len(sys.argv) > 1 else "pdfdrill-figure.json")
    errs = figspec.validate(spec)
    if errs:
        for e in errs:
            print("SPEC ERROR:", e)
        sys.exit(1)
    spec["_outputformat"] = sys.argv[3] if len(sys.argv) > 3 else "pdf"
    out = sys.argv[2] if len(sys.argv) > 2 else "pdfdrill-figure.mp"
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(emit(spec))
    print("wrote", out)
